# code: language=ansible
---

- name: "VPN | Install | Apt"
  ansible.builtin.apt:
    name: "{{ vpn_packages }}"
    state: "present"
    update_cache: false
    force_apt_get: true
    cache_valid_time: 3600
  become: true
  tags:
    - vpn
    - vpn-install
