# code: language=ansible
---

- name: "VPN | Install | Dnf"
  ansible.builtin.dnf:
    name: "{{ vpn_packages }}"
    state: "present"
    update_cache: false
  become: true
  tags:
    - vpn
    - vpn-install
