# code: language=ansible
---

- name: "VPN | Always | Install dependencies | Apt"
  ansible.builtin.apt:
    name: "{{ vpn_always_packages }}"
    state: present
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
  become: true
  tags:
    - always
